# -*- coding: utf-8 -*-
"""panda_tricks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4ygS_X32yny_NsygmyIw-kYAG7dNOby
"""

import pandas as pd

import numpy as np

#Series (Observe o indice do lado esquerdo)
s1 = pd.Series([1,2,-5,0])

print(s1)

s1.values

s1.index

s2=pd.Series([1,2,-5,0],index=['Nome','Endereço','CEP','Telefone'])

s2

s2.index

s2['a']=1000

print(s2)

s2[s2>0]

#Algebra
s2*2

s2

s2.isnull()

s2.notnull()

dados={'estado':['SP','MG','PR','SP','BA','CE'],
       'ano':[2019,2019,2019,2020,2020,2020],
       'pop':[45.9,21.2,16.9,46.6,21.4,17.3]}
df1=pd.DataFrame(dados)

print(df1)

#Pra pegar quantidade do head pra baixo
df1.head(2)

#Pra pegar quantidade de button(tail) pra cima
df1.tail(2)

df1.sample(2)

df2=pd.DataFrame(dados,columns=['ano','estado','pop'])

print(df2)

#Pra acrescentar mais uma coluna
df2['Auxilio_Pandemia']=500

print(df2)

#Se quiser q ele dê uma lista numerada, tipo uma contagem, ex: primary key
df2['user_id']=np.arange(6)

print(df2)

df3=pd.DataFrame(dados,columns=['estado', 'ano', 'user_id', 'Auxilio_Pandemia','pop'])

print(df2)

